[package]
name = "jova-core"
version = "0.0.1"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
description = "Public Rust API for jovawallet-core"

[lib]

[dependencies]
jova-core-primitives.workspace = true
jova-core-chains.workspace = true
serde = { workspace = true, features = ["derive"] }
serde_json.workspace = true
thiserror.workspace = true

[dev-dependencies]
hex.workspace = true
serde_json.workspace = true
